### PR TITLE
Changed registration behavior to register with inventory_hostname so …

### PR DESCRIPTION
**Pull request by kyleabenson**
…Ansible and Insights mappings are the same

Changed author to Red Hat as DVarga left

### CODE REVIEW

**Review by gavin-romig-koch — CHANGES_REQUESTED** [review]
I agree that being able to set the display name is important and that we should figure out a way to get that done.
(This got really long, if you want/need to talk about any of this, please just contact me).
But there are a number of problems with your patch.

Playbooks should try to be idempotent.  If you run the same playbook twice, it should do nothing the second time except check that the system is still set up the same. 
It looks like your changes will cause the playbook to error out the second time it is run.  I think this can be fixed by just taking out the "fail" task. 

Next, I'm pretty sure redhat-access-insights will error out if you run it with the --register option and the .unregister file exists.  You need to put the check for the unregister file back in.

While adding the option to set the display name is good, unconditionally setting it to inventory_hostname is problematic for several reasons.  "inventory_hostname" is just whatever name is in the inventory, and may not be what someone wants in every case.  Instead, add a "display_name"  parameter to the roll (see http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html) that allows one to set the display name without doing it unconditionallyi.

Finally it's crufty to leave commented out code in the playbook without explaining why it's still there and why it's commented out,.

**Comment by kyleabenson** [comment]
Hey thanks @gavin-romig-koch -- good feedback and I'll make the changes.

re: setting a display_name var in the role -- I can definitely do that but I think the default value for that var should be {{ inventory_hostname }}. Any objections?

If we place this var in defaults/main.yml it'll make it easy for someone to override elsewhere based on variable precedence if they WANT to override it. If we don't set this as the default, people are likely creating an unusable registration for running future Insights playbooks via Ansible Engine or Tower.

EX: If you run registration in AWS it will by default assume the hostname which is the internal hostname and has no mapping to the public IPs most users use or alias against.

**Comment by gavin-romig-koch** [comment]
@kyleabenson I do object.  

If we make the default {{ inventory_hostname }} we fix the AWS case, but we break some existing currently working cases in a way that is not easy to fix (because after you set display name, it's hard/imposible to unset).

**Comment by jharting** [comment]
@kyleabenson @gavin-romig-koch FYI making it possible to rename a system in the Insights UI (i.e. to manually fix inconsistency between Insights and Ansible inventory) has been on the backlog for quite a while. It is planned to finally roll out some time next week (in beta).

**Comment by kyleabenson** [comment]
@gavin-romig-koch Maybe you're referring to existing registered systems when you said existing working cases? To me, the obvious benefit of using something like Ansible almost implores us to say the default behavior should be using the {{ inventory_hostname }} variable.

Another clear use case here is that if people have Ansible aliases setup, you'd  want to easily recognize those systems in Insights by that alias as well. 

I think the debate here is more on what the source of truth should be for the hostnames. If a Ansible or Ansible Tower defers to a CMDB or other, I feel like Insights should here as well because we're not treating Insights as a way to source inventory. 

That's maybe more my own gripe, so I'm closing the PR. I'll have to create a playbook that does this elsewhere for demoing to partners/customers etc.

**Comment by gavin-romig-koch** [comment]
@kyleabenson 
While the "name" of a system in Ansible's inventory is often (almost always) it's hostname, it doesn't have to be it's actual hostname, or even a usable name at all; it can be an ip-address, a local alias (see 'jumper' example in  http://docs.ansible.com/ansible/latest/intro_inventory.html ), or an ssh alias.  It doesn't have to be consistent from one inventory file to the next, or from one control host to the next.  For example, when you run a playbook against 127.0.0.1, inventory_hostname is 127.0.0.1.

>> Maybe you're referring to existing registered systems when you said existing working cases? 

No.   The most likely users of this insights-role, are already users of the redhat-access-insights command.  These users will know/expect that the role is just a wrapper around the command, and will expect that the options and their defaults map simply from the role to the command.   These users are less likely to carefully read the role's documentation, and are more likely to be surprised by this change to the default.  That's what i meant by existing working cases.

If redhat-access-insights didn't already exist, and didn't already default this option a specific way, and the role was the first place we were making the decision "Hmm, what should the default be?", we might make a different choice for this default, but we already have a default, and I don't think that the advantages of changing the default outweigh its disadvantages in this case.  

I think the best move at this point is to add the display name option to the role, defaulting exactly the same way as "redhat-access-insights".  And document clearly in the role documentation that there are a number of cases, like the AWS case, where you don't want the default, and you want to explicitly set display name, and inventory_hostname is often, but not always, a good choice.

**Pull request closed without merging**
